### ISSUE TITLE
How exactly to import this ? 

### ISSUE THREAD

**Issue by DavidAwad** [turbomanage/basic-http-client#21]
I can't seem to figure out how to get this imported into my project. I have the jar file being compiled in  the gradle build script. I just can't import it in my activities to use them.

**Comment by turbomanage** [comment]
Which IDE / version are you using? Can you successfully import any other jars via gradle?

**Comment by DavidAwad** [comment]
I'm using newest android studio, just confused how to import this as a jar file. thanks!

**Comment by turbomanage** [comment]
When you add the dependency to your build.gradle file as instructed on the README page, you should see "http-client-android-0.89" show up as a folder under External Libraries in the Project view. Are you not seeing this?

**Comment by Onasis007** [comment]
Review

**Comment by turbomanage** [comment]
Needs more info, closing for now.
