### ISSUE TITLE
Where can I get the downloading url of the full javadoc files? 

### ISSUE THREAD

**Issue by Warnier-zhang** [turbomanage/basic-http-client#23]

**Comment by turbomanage** [comment]
You can find the javadoc jar using search.maven.org:
http://search.maven.org/remotecontent?filepath=com/turbomanage/basic-http-client/http-client-java/0.89/http-client-java-0.89-javadoc.jar

**Comment by Warnier-zhang** [comment]
Thanks for your answer and for your great work!
